### ISSUE TITLE
RSS redirects to edit

### ISSUE THREAD

**Issue by zigomir** [vasinov/almanac#12]
I'm subscribed to Problems & Solutions blog and today I was redirected on to http://www.vasinov.com/blog/8/edit when clicking on http://www.vasinov.com/blog/8

I suppose this has to do something with new Almanac version so I' writing it here. Didn't have enough time yet to make a pull request.

**Comment by vasinov** [comment]
I fixed the problem in 0.9.1: RSS feed had links to IDs of posts instead of their slugs.

Thank you for reporting it.
